title: ZenWave360
# email: ivangsa@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  ZenWave 360: DDD and API-First Modeling Tools for Modern Distributed Applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  ivangsa


# Site settings
permalink: /blog/:title/
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"
date_format: "%b %-d, %Y"

# Theme settings
remote_theme: just-the-docs/just-the-docs
search_enabled: true
logo: "https://github.com/ZenWave360/.github/raw/main/logos/zenwave360/zenwave360.png"
aux_links:
  "See on GitHub":
    - "//github.com/zenwave360/zenwave-code-generator"
ga_tracking: G-PWPE0ZF877
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true by default)

footer_content: "ZenWave360 &copy; 2022 - Domain Driven Design (DDD) and API-First for Event Driven Microservices"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
